services:
  backend:
    image: femzytr/dynamicdeployment-backend:latest
    container_name: deployment-practice-backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      PORT: 3001
      MONGO_URI: mongodb://mongo:27017/deployment_practice
    depends_on:
      - mongo

  frontend:
    image: femzytr/dynamicdeployment-frontend:latest
    container_name: deployment-practice-frontend
    restart: always
    ports:
      - "8081:80"
    depends_on:
      - backend

  mongo:
    image: mongo:7
    container_name: deployment-practice-mongo
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: